### ISSUE TITLE
Correctly sort version numbers

### ISSUE THREAD

**Issue by chloekek** [chloekek/crai#6]
Currently we sort version numbers textually, but it should be done properly. Because of this, 3.4 is considered higher than 3.10.

This is difficult with SQLite, but there are two possible solutions:

 - Harness [custom collations][customcoll], but DBDish doesn’t support this right now.
 - Store normalized version numbers, e.g. 00030004 instead of 3.4 and 00030010 instead of 3.10.

[customcoll]: https://www.sqlite.org/c3ref/create_collation.html

**Comment by AlexDaniel** [comment]
Possibly related: https://github.com/osquery/osquery/issues/5196

**Comment by chloekek** [comment]
Done! Using the normalization tactic.
